"""empty message

Revision ID: 5d8a28b752c1
Revises: 2df76ecffab8
Create Date: 2022-08-12 14:51:07.388072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d8a28b752c1'
down_revision = '2df76ecffab8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('genre', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artist', 'genre')
    # ### end Alembic commands ###
