"""empty message

Revision ID: b3f93e0c074e
Revises: e385be439b77
Create Date: 2022-08-11 16:33:46.753632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3f93e0c074e'
down_revision = 'e385be439b77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('venue_name', sa.String(length=50), nullable=True))
    op.add_column('shows', sa.Column('artist_name', sa.String(length=200), nullable=True))
    op.add_column('shows', sa.Column('image_link', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shows', 'image_link')
    op.drop_column('shows', 'artist_name')
    op.drop_column('shows', 'venue_name')
    # ### end Alembic commands ###
